#!/bin/bash

echo "🚀 Queue Management System - GitHub Setup & DigitalOcean Deployment"
echo "=================================================================="
echo ""

echo "📋 Step 1: Create GitHub Repository"
echo "1. Go to https://github.com/new"
echo "2. Repository name: queue-management-system"
echo "3. Description: Queue Management System - Go web application with real-time updates"
echo "4. Set to Public"
echo "5. DO NOT initialize with README (we already have files)"
echo "6. Click 'Create repository'"
echo ""

echo "📋 Step 2: Push Code to GitHub"
echo "Run these commands in your terminal:"
echo ""
echo "git remote add origin https://github.com/YOUR_USERNAME/queue-management-system.git"
echo "git push -u origin main"
echo ""

echo "📋 Step 3: Deploy to DigitalOcean App Platform"
echo "1. Go to https://cloud.digitalocean.com/apps"
echo "2. Click 'Create App'"
echo "3. Select 'GitHub' as source"
echo "4. Choose your repository: queue-management-system"
echo "5. Select branch: main"
echo "6. Enable 'Auto-deploy on push'"
echo "7. DigitalOcean will detect the Dockerfile automatically"
echo "8. Review settings:"
echo "   - App name: queue-management-system"
echo "   - Region: New York (NYC) or your preferred region"
echo "   - Plan: Basic (\$5/month)"
echo "9. Click 'Create Resources'"
echo ""

echo "⏱️  Deployment usually takes 5-10 minutes"
echo "🎉 Your app will be available at: https://queue-management-system-xxxxx.ondigitalocean.app"
echo ""

echo "💡 Pro Tips:"
echo "- Your app runs on port 8080 (automatically configured)"
echo "- SSL certificate is provided automatically"
echo "- Auto-scaling is enabled"
echo "- Logs are available in the DigitalOcean dashboard"
