name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21

    - name: Download Go dependencies
      run: go mod download
        
    - name: Run Go tests
      run: go test -v ./...
      
    - name: Build application
      run: go build -v ./cmd/web
      
    - name: Verify build
      run: |
        echo "✅ Go build successful"
        echo "✅ All tests passed"
        echo "🚀 Ready for DigitalOcean deployment"
