name: Deploy to DigitalOcean App Platform

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        go mod download
        npm install
        
    - name: Run tests
      run: go test -v ./...
      
    - name: Build application
      run: go build -v ./cmd/web
      
    - name: Deploy to DigitalOcean App Platform
      if: github.ref == 'refs/heads/main'
      uses: digitalocean/app_action@v1.1.5
      with:
        app_name: queue-management-system
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
